### ISSUE TITLE
Please add Disk Browser Focus to API?

### ISSUE THREAD

**Issue by esaruoho** [renoise/tools#124]
Is it true that the Renoise API 5 does not afford us control over whether Disk Browser is focused or not? 

I see `renoise.app().window.disk_browser_is_visible, _observable` but, while having this is good, I would like to make the disk browser visible _and_ focus the Keyboard to the Disk Browser.

P.S. Would be good to be able to enter Extended Disk Browser mode, too.

@connerbw @snabeljoel @emuell

**Comment by bjorn-nesby** [comment]
Yes, there is no dedicated method or API to query or control focus in Renoise. 

I think it would make sense to add this, not just to a single component (disk browser), but throughout the API, and with granular support in the ViewBuilder API

**Comment by esaruoho** [comment]
@bjorn-nesby i fully agree. Having a lot of cursor focus would be really beneficial for scripting.

Such as: focus on disk browser, focus on instrument box, focus on pattern matrix, focus on pattern editor.

**Comment by esaruoho** [comment]
would still be pretty cool to have :)

**Comment by esaruoho** [comment]
hi, still here, still a good feature to have @bjorn-nesby
