### ISSUE TITLE
xStream install raises notifiers error

### ISSUE THREAD

**Issue by leonardreidy** [renoise/tools#146]
[RenoiseLog.txt](https://github.com/renoise/xrnx/files/2247063/RenoiseLog.txt)
During install of xStream with Renoise V3.1.1 on Ubuntu 16.04.5 LTS (xenial), an error occurs. 

Steps to reproduce: 
- Drop xrnx file onto main Renoise UI
- Error dialog is raised with following error message:
'~/.renoise/V3.1.1/Scripts/Tools/com.renoise.xStream.xrnx/main.lua' failed in one of its notifiers.
Error Message: The notifier will be disabled to prevent further errors.

Closer inspection at command line discloses the following log message: 

ScriptingEngine: main.lua:155: attempt to index field 'preferences' (a nil value) stack traceback:
	main.lua:155: in function <main.lua:153>

See attached log for more information!
Thanks for all your great work on xStream! Spectacular tool. :)

**Comment by bjorn-nesby** [comment]
Has been fixed, but not yet released
https://github.com/renoise/xrnx/issues/102
