### ISSUE TITLE
Getting the current directory of the disk browser

### ISSUE THREAD

**Issue by defaultxr** [renoise/tools#157]
Hi.

I'm writing a Renoise script that will automatically create a drumset by selecting random files from a directory. I feel like it would be very convenient if the script was able to see which directory was open in the disk browser and create the drumset from that, rather than requiring the user to select a directory manually each time.

tl;dr: Please add the ability to see which folder is currently open in the disk browser.

Bonus: Adding the ability to see which files are selected in the disk browser would be even better.

**Comment by esaruoho** [comment]
i'm also looking for a method of telling os.execute(Terminal.app) the folder the Disk Browser is in.
would be a great feature to have.

**Comment by defaultxr** [comment]
Hi - has this been implemented in 3.5.0? I'm looking at the updated Lua API docs for v3.5.0 and I'm seeing `disk_browser_is_visible` and `disk_browser_category` but I don't see any documentation for the disk browser's current directory/directories. Not sure if I'm missing something or if it has a different name or similar.

**Comment by esaruoho** [comment]
@emuell did you close it because it's a "no, api isn't gonna have this", or..?
