### ISSUE TITLE
HMTL Documentation Is Out Of Date In Download

### ISSUE THREAD

**Issue by duncanhemingway** [renoise/tools#159]
The html version of the docs in the download package have not been updated since 2019: [http://files.renoise.com/xrnx/XrnxStarterPack330.zip](http://files.renoise.com/xrnx/XrnxStarterPack330.zip)

**Comment by emuell** [comment]
Just have fixed that and upload new docs for RNS 3.4 https://github.com/renoise/xrnx/commit/950617b2cb36fb7a261f863b17ce1bf1e54630ec
