### ISSUE TITLE
Html documentation generation requires legacy PHP

### ISSUE THREAD

**Issue by jcpst** [renoise/tools#53]
I tried running the documentation generator and the following error occurred:

```
PHP Warning:  preg_replace(): The /e modifier is no longer supported, use preg_replace_callback instead in /home/joe/git/xrnx/Xtra/HtmlGen/api_to_html.php on line 152
```

And it spit out .html pages with no documentation.

I have PHPv7 on my machine. I've never touched PHP code before, so I looked at their docs and found [this](http://php.net/manual/en/reference.pcre.pattern.modifiers.php#reference.pcre.pattern.modifiers.eval).

So I changed [api_to_html.php](https://github.com/renoise/xrnx/blob/master/Xtra/HtmlGen/api_to_html.php#L152) at L152 to this:

``` php
$markdown = preg_replace_callback(
    '/(={4,}|-{4,})\n(.*?)(={4,}|-{4,})\n/s',
    function ($m) {
        return "header_transform('$m[1]', '$m[2]')";
    },
    $markdown
);
```

And it worked...mostly. The `header_transform` function came out as plain text on the .html page:

```
header_transform('============================================================================', 'Renoise Script Debugging HowTo ') In addition to the usual print....
```

**Comment by dac514** [comment]
It's a warning, not an error. You can suppress it using the `@` character. Example:

`$markdown = @preg_replace('/(={4,}|-{4,})\n(.*?)(={4,}|-{4,})\n/se', "header_transform('$1', '$2')", $markdown);`

For your fix: `header_transform` is a function in global space found a bit higher up in the file (line ~51). You must remove the quotes which is converting it to a string. Try:

``` php
$markdown = preg_replace_callback(
    '/(={4,}|-{4,})\n(.*?)(={4,}|-{4,})\n/s',
    function ($m) {
        return header_transform('$m[1]', '$m[2]');
    },
    $markdown
);
```

**Comment by jcpst** [comment]
Yep, raised this issue too soon, just figured out that fix myself. Thank you!

To get `api_to_html.php` building the docs with PHP7, Would it be preferable to suppress the warning, or update that statement?

**Comment by dac514** [comment]
Updating the statement is preferable. :)
